require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FollowingsController do

  # This should return the minimal set of attributes required to create a valid
  # Following. As you add validations to Following, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "create" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FollowingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all followings as @followings" do
      following = Following.create! valid_attributes
      get :index, {}, valid_session
      assigns(:followings).should eq([following])
    end
  end

  describe "GET show" do
    it "assigns the requested following as @following" do
      following = Following.create! valid_attributes
      get :show, {:id => following.to_param}, valid_session
      assigns(:following).should eq(following)
    end
  end

  describe "GET new" do
    it "assigns a new following as @following" do
      get :new, {}, valid_session
      assigns(:following).should be_a_new(Following)
    end
  end

  describe "GET edit" do
    it "assigns the requested following as @following" do
      following = Following.create! valid_attributes
      get :edit, {:id => following.to_param}, valid_session
      assigns(:following).should eq(following)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Following" do
        expect {
          post :create, {:following => valid_attributes}, valid_session
        }.to change(Following, :count).by(1)
      end

      it "assigns a newly created following as @following" do
        post :create, {:following => valid_attributes}, valid_session
        assigns(:following).should be_a(Following)
        assigns(:following).should be_persisted
      end

      it "redirects to the created following" do
        post :create, {:following => valid_attributes}, valid_session
        response.should redirect_to(Following.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved following as @following" do
        # Trigger the behavior that occurs when invalid params are submitted
        Following.any_instance.stub(:save).and_return(false)
        post :create, {:following => { "create" => "invalid value" }}, valid_session
        assigns(:following).should be_a_new(Following)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Following.any_instance.stub(:save).and_return(false)
        post :create, {:following => { "create" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested following" do
        following = Following.create! valid_attributes
        # Assuming there are no other followings in the database, this
        # specifies that the Following created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Following.any_instance.should_receive(:update).with({ "create" => "MyString" })
        put :update, {:id => following.to_param, :following => { "create" => "MyString" }}, valid_session
      end

      it "assigns the requested following as @following" do
        following = Following.create! valid_attributes
        put :update, {:id => following.to_param, :following => valid_attributes}, valid_session
        assigns(:following).should eq(following)
      end

      it "redirects to the following" do
        following = Following.create! valid_attributes
        put :update, {:id => following.to_param, :following => valid_attributes}, valid_session
        response.should redirect_to(following)
      end
    end

    describe "with invalid params" do
      it "assigns the following as @following" do
        following = Following.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Following.any_instance.stub(:save).and_return(false)
        put :update, {:id => following.to_param, :following => { "create" => "invalid value" }}, valid_session
        assigns(:following).should eq(following)
      end

      it "re-renders the 'edit' template" do
        following = Following.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Following.any_instance.stub(:save).and_return(false)
        put :update, {:id => following.to_param, :following => { "create" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested following" do
      following = Following.create! valid_attributes
      expect {
        delete :destroy, {:id => following.to_param}, valid_session
      }.to change(Following, :count).by(-1)
    end

    it "redirects to the followings list" do
      following = Following.create! valid_attributes
      delete :destroy, {:id => following.to_param}, valid_session
      response.should redirect_to(followings_url)
    end
  end

end
